### ISSUE TITLE
Have a build command

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/HookTest#57]
- Create a manifest at the end of the test with passing files and general results listed in #56 
- Create a "release" (have a look at travis documentation for that and see what's best practices then list them here for implementation)

**Comment by sonofmun** [comment]
We will probably need to add something that looks like this to the .travis.yml file:

```
before_deploy: RUN SOMETHING LIKE hookclean.py.erb
deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file_glob: true
  file: DIRECTORY_WITH_PASSING_FILES/*
  skip_cleanup: true
  on:
    tags: true
```

More information here: https://docs.travis-ci.com/user/deployment/releases/
